# Test against the latest version of this Node.js version
environment:
  matrix:
    - nodejs_version: "LTS"
    - nodejs_version: "Current"

# Install scripts. (runs after repo cloning)
install:
  # Install latest chrome
  - choco install googlechrome
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # Output useful info for debugging.
  - node --version
  - npm --version
  # install modules
  - npm install
  - npm run bootstrap -- --no-ci

# Post-install test scripts.
test_script:
  # run tests
  - npm run test:node
  - npm run test:chrome
  - node_modules\.bin\webdriver-manager update --gecko false --version.chrome 2.37
  - npm run test:protractor -- --directConnect
  - npm run test:puppeteer

# Don't actually build.
build: off
