version: '3.7'
services:
  web-server:
    image: nginx:alpine
    container_name: web-server
    volumes:
      - ./test/rendering:/usr/share/nginx/html
    ports:
      - 8080:80

  selenium:
    image: selenium/standalone-chrome:3.11.0
    container_name: selenium
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
