'use strict';

module.exports = {
  url: 'http://localhost:9676/examples/requirejs/index.html',
  glob: 'examples/requirejs/*.spec.js',
  'instrument.exclude': [
    '**/coverage/**',
    '**/external/**',
    '**/autogenerated/**',
    '**/*.(html|css|json|txt|ttf|woff|svg)',
    '*require*.js',
    '*sinon*.js',
    '*chai*.js',
    '**/*.js',
  ],
  'instrument.coverage.exclude': [
    '**/coverage/**',
    '**/external/**',
    '**/autogenerated/**',
    '**/*.(html|css|json|txt|ttf|woff|svg)',
    '*require*.js',
    '*sinon*.js',
    '*chai*.js',
    '**/*.spec.js',
  ],
};
