module.exports = {
  'instrument.exclude': [
    '**/coverage/**',
    '**/external/**',
    '**/autogenerated/**',
    '**/*.(html|css|json|txt|ttf|woff|svg)',
    '*require*.js',
    '*sinon*.js',
    '*chai*.js',
    '**/*.js',
  ],
};
