module.exports = {
  url: {
    description: 'Url to html file',
    type: 'string',
    default: null,
  },
  'transform.typescript.config': {
    description: 'Typescript config file',
    default: 'tsconfig.json',
    type: 'string',
  },
  'transform.typescript.babelOptions': {
    description: 'Typescript babel options',
    default: {},
    type: 'object',
  },
  'transform.include': {
    description: 'Transform files with babel?',
    default: [],
    type: 'array',
  },
  'transform.exclude': {
    description: 'Exclude glob',
    default: [],
    type: 'array',
  },
  'transform.defaultExclude': {
    description: 'Default exclude glob',
    default: [
      '**/coverage/**',
      '**/external/**',
      '**/autogenerated/**',
      '**/*.{html,css,json,txt,ttf,woff,svg}',
      '**/*require*.js',
      '**/*sinon*.js',
      '**/*chai*.js',
    ],
    type: 'array',
  },
  'mocha.bail': {
    description: 'Bails on failure',
    default: true,
    type: 'boolean',
  },
  'mocha.ui': {
    description: 'Test interface',
    default: 'bdd',
    type: 'string',
  },
  'mocha.timeout': {
    description: 'Timeout',
    default: 2000,
    type: 'number',
  },
  'mocha.useColors': {
    description: 'Use colors in output',
    default: true,
    type: 'boolean',
  },
  'mocha.reporter': {
    description: 'Reporter',
    default: 'min',
    type: 'string',
  },
  'client.port': {
    description: 'Chrome port',
    default: 9222,
    type: 'number',
  },
  'chrome.launch': {
    description: 'Launch Chrome',
    default: true,
    type: 'boolean',
  },
  'chrome.devtools': {
    description: 'Open Chrome with dev tools',
    default: false,
    type: 'boolean',
  },
  'chrome.port': {
    description: 'Chrome port',
    default: 9222,
    type: 'number',
  },
  'chrome.chromeFlags': {
    description: 'Chrome flags',
    default: ['--headless', '--disable-gpu', '--allow-file-access-from-files'],
    type: 'array',
  },
  'http.port': {
    description: 'Listen on this http port',
    default: 9676,
    type: 'number',
  },
  'http.root': {
    description: 'Root folders to serve',
    default: ['./'],
    type: 'array',
  },
  'http.rewrite': {
    description: 'Rewrite url(s)',
    default: {},
    type: 'object',
  },
  'nyc.include': {
    description: 'Instrument files with babel?',
    default: [],
    type: 'array',
  },
  'nyc.exclude': {
    description: 'Exclude glob',
    default: [],
    type: 'array',
  },
  'nyc.tempDirectory': {
    description: 'Directory to output raw coverage information to',
    default: './coverage/.nyc_output',
    type: 'string',
  },
  'nyc.reporter': {
    description: 'Coverage reporter(s) to use',
    default: ['lcov', 'text-summary'],
    type: 'array',
  },
  'nyc.reportDir': {
    description: 'Directory to output coverage reports in',
    default: 'coverage',
    type: 'string',
  },
  interactive: {
    description: 'Run in interactive mode',
    default: false,
    type: 'boolean',
    alias: 'i',
  },
};
